version: "3.6"

services:
    web:
        build: ./docker
        ports:
            - "80:80"
        volumes:
            - ./:/siteroot
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: acg_portal
            MYSQL_USER: acg_root
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
    test-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: acg_portal_test
            MYSQL_USER: acg_root
            MYSQL_PASSWORD: password
volumes:
    dbdata:
